### ISSUE TITLE
Support text overflow?? 

### ISSUE THREAD

**Issue by jgmartinss** [cetorres/dropdown_formfield#12] opened 2020-04-28 20:55 UTC

**Comment by RafaelPlantard** [comment] 2020-05-03 18:42
I guess it would be nice support it avoiding the following error:
![IMG_21FCAC057414-1](https://user-images.githubusercontent.com/5968478/80922601-a13b2a80-8d54-11ea-94f7-0cbf19ac777b.jpeg)

**Comment by RafaelPlantard** [comment] 2020-05-03 18:42
Maybe duplicate of #8 issue.

**Closed as completed** 2020-05-07 15:39 UTC
